<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title> Cadastro de dados </title>
</head>

<body>
    <form action="" method="post">
        <label for="nome"></label>
        <input type="text" name="" id="nome" value=<?= $this->nome?> placeholder="Nome completo aqui">
        <label for="cpf"></label>
        <input type="text" name="" id="cpf" value=<?= $this->cpf?> placeholder="XXX.XXX.XXX-XX">
        <label for="email"></label>
        <input type="text" name="" id="email" value=<?= $this->email?> placeholder="xxxxx@xxxx.xxx">
        <label for="telefone"></label>
        <input type="text" name="" id="telefone" value=<?= $this->telefone?> placeholder="(XX) XXXXX-XXXX">
        <label for="idade"></label>
        <input type="text" name="" id="idade" value=<?= $this->idade?> placeholder="Sua idade aqui">
        <label for="logradouro"></label>
        <input type="text" name="" id="logradouro" value=<?= $this->logradouro?> placeholder="Seu logradouro aqui">
        <label for="CEP"></label>
        <input type="text" name="" id="CEP" value=<?= $this->CEP?> placeholder="Digite seu CEP aqui">
        <label for="numero"></label>
        <input type="text" name="" id="numero" value=<?= $this->numero?> placeholder="Número da sua residencia">
        <label for="bairro"></label>
        <input type="text" name="" id="bairro" value=<?= $this->bairro?> placeholder="Digite seu bairro aqui">
        <label for="cidade"></label>
        <input type="text" name="" id="cidade" value=<?= $this->cidade?> placeholder="Informe sua cidade">
        <label for="estado"></label>
        <input type="text" name="" id="estado" value=<?= $this->estado?> placeholder="Informe seu estado">
    </form>

</body>

</html>